trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  DefinitionName: 'centralpackageanagement-build'

steps:
- task: NuGetToolInstaller@1

- task: ArtifactoryNuGet@2
  inputs:
    command: 'restore'
    artifactoryService: 'Artifactory'
    targetResolveRepo: 'alpha-nuget-virtual'
    solutionPath: 'CentralPackageManagementExample/*.sln'
    collectBuildInfo: true
    buildName: '$(DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

- task: ArtifactoryNuGet@2
  inputs:
    command: 'push'
    artifactoryService: 'Artifactory'
    targetDeployRepo: 'alpha-nuget-virtual'
    pathToNupkg: '*.nupkg'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true

- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'Artifactory'
    buildName: '$(DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'soleng-maharship'
    command: 'jf bs $(DefinitionName) $(Build.BuildNumber) --vuln'


