# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: NugetBuild
on: [push]

jobs:
  build:
    env:
      JF_URL: ${{ secrets.JF_URL }}
      JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      SERVER_ID: "rtsaas"
      REPO: "alpha-nuget-virtual"
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Setup JFrog CLI 
      uses: jfrog/setup-jfrog-cli@v3.4.0
    - name: JFrog CLI config
      run: jf c add $SERVER_ID --url=$JF_URL --access-token=$JF_ACCESS_TOKEN --interactive=false
    - name: Ping JFrog CLI
      run: jf rt ping --server-id=$SERVER_ID
    - name: NugetConfig
      run: jf nugetc --server-id-resolve=$SERVER_ID --repo-resolve=$REPO
    - name: location
      run: 
        pwd
        ls
        cd CentralPackageManagementExample/
    - name: Restore dependencies
      run: jf nuget restore 
